name: deploy on push 
on:   
  push:     
  branches:       
- main 
jobs:   
  deploy-app:     
  runs-on: ubuntu-latest     
  steps:       
    - name: check out the code to build server         
      uses: actions/checkout@v2       
    - name: copy file to server         
      uses: appleboy/scp-action@master         
    with:           
      host: ${{ secrets.HOST: ec2-44-204-159-49.compute-1.amazonaws.com }}           
      username: ${{ secrets.SSH_USER_NAME: webadmin }}           
      port: ${{ secrets.SSH_PORT: 22 }}           
      key: ${{ secrets.SSH_KEY: }}           
      source: "./*"           
      target: "/var/www/html/" 